### ISSUE TITLE
Mosaic integration breaks when no bed is available

### ISSUE THREAD

**Issue by anderspitman** [iobio/bam.iobio#12]
This is the line: https://github.com/iobio/bam.iobio/blob/6b6970e32cc670e1e263e05cdf43022588fcb678/index.html#L331

This can be tested by launching bam from https://mosaic-staging.chpc.utah.edu

**Comment by anderspitman** [comment]
Specifically this sample: https://mosaic-staging.chpc.utah.edu/#/projects/33/samples/112/overview

**Comment by YangQi007** [comment]
@anderspitman @AlistairNWard I tried to reproduce this bug, but I found that I didn't have the access permission.

**Comment by anderspitman** [comment]
@YangQi007 I just added you to the project. Can you try again?

**Comment by anderspitman** [comment]
@YangQi007 this one is fixed, right?

**Comment by YangQi007** [comment]
> @YangQi007 this one is fixed, right?

Yes.
