### ISSUE TITLE
Add static resources

### ISSUE THREAD

**Issue by anderspitman** [iobio/bam.iobio#15]
We need to add the home page images and default BED files. Lets place these files in an S3 bucket, and use full URLs to link to them from the app.

**Comment by YangQi007** [comment]
I have these files and images. Do you want me to send them to you? Or I can do it if you can point me to the S3 bucket.

**Comment by anderspitman** [comment]
Go ahead and upload them to this bucket here: s3://static.iobio.io/prod/bam.iobio.io/
